name = "NTNk"
uuid = "530fd2b5-bc52-54ba-93c2-82eb6468edee"
authors = ["Velimir V Vesselinov (monty) <velimir.vesselinov@gmail.com>"]
version = "0.1.1"

[deps]
NMFk = "e40cd9e2-a1df-5d90-a1fa-603fdc3dbdd8"
NTFk = "1226e131-0b97-51f8-8a3f-c1798118cd52"

[compat]
julia = "≥ 1.0.0"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
